
# database configuration
[db]
user = "root"
password = "123456"
sql_type = "mysql"
database_name = "godoing"
server_addr = "localhost"
port = 3306

[server]
ip = "127.0.0.1"
port = 8081


# log configuration
[log]
# debug,trace,info,warn,error,fatal,panic
level = "info"

[system_config]
version = "V1.0"

